language: node_js
node_js:
  - v7
  - v6
  - v5
  - v4

before_install:
  - stty cols 80

dist: trusty
sudo: required

addons:
  firefox: latest
  apt:
    sources:
     - google-chrome
    packages:
     - google-chrome-stable

before_script:
  - "export DISPLAY=:99.0"
  - "Xvfb :99 -screen 0 1920x1080x8&"
  - sleep 3

after_success:
  - './node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls'
