# Dependencies
markdown:          kramdown
highlighter:       pygments

# Server
source:            docs
destination:       _gh-pages
encoding:          UTF-8

# Filtering Content
published: false

repo:              https://github.com/gitscrum/slim-grid