# Dependencies
markdown:          kramdown
highlighter:       pygments

# Permalinks
permalink:        pretty

# Server
source:            ./docs
baseurl:           /
destination:       ./_gh-pages
host:              0.0.0.0
port:              9001
encoding:          UTF-8
url:               http://localhost:9001

# Custom vars
current_version:   0.2.0
repo:              https://github.com/gitscrum/slims-grid
